interface CountryFlag {
  name: string;
  abrev: string;
}

const COUNTRIES_FLAGS: CountryFlag[] = [
  { name: 'Afganistán', abrev: 'af' },
  { name: 'Albania', abrev: 'al' },
  { name: 'Alemania', abrev: 'de' },
  { name: 'Andorra', abrev: 'ad' },
  { name: 'Angola', abrev: 'ao' },
  { name: 'Anguila', abrev: 'ai' },
  { name: 'Antártida', abrev: 'aq' },
  { name: 'Antigua y Barbuda', abrev: 'ag' },
  { name: 'Antillas Holandesas', abrev: 'an' },
  { name: 'Arabia Saudí', abrev: 'sa' },
  { name: 'Argelia', abrev: 'dz' },
  { name: 'Argentina', abrev: 'ar' },
  { name: 'Armenia', abrev: 'am' },
  { name: 'Aruba', abrev: 'aw' },
  { name: 'Australia', abrev: 'au' },
  { name: 'Austria', abrev: 'at' },
  { name: 'Azerbaiyán', abrev: 'az' },
  { name: 'Bahamas', abrev: 'bs' },
  { name: 'Bahrein', abrev: 'bh' },
  { name: 'Bangladesh', abrev: 'bd' },
  { name: 'Barbados', abrev: 'bb' },
  { name: 'Bélgica', abrev: 'be' },
  { name: 'Belice', abrev: 'bz' },
  { name: 'Benin', abrev: 'bj' },
  { name: 'Bermudas', abrev: 'bm' },
  { name: 'Bielorrusia', abrev: 'by' },
  { name: 'Birmania', abrev: 'mm' },
  { name: 'Bolivia', abrev: 'bo' },
  { name: 'Bosnia y Herzegovina', abrev: 'ba' },
  { name: 'Botswana', abrev: 'bw' },
  { name: 'Brasil', abrev: 'br' },
  { name: 'Brunei', abrev: 'bn' },
  { name: 'Bulgaria', abrev: 'bg' },
  { name: 'Burkina Faso', abrev: 'bf' },
  { name: 'Burundi', abrev: 'bi' },
  { name: 'Bután', abrev: 'bt' },
  { name: 'Cabo Verde', abrev: 'cv' },
  { name: 'Camboya', abrev: 'kh' },
  { name: 'Camerún', abrev: 'cm' },
  { name: 'Canadá', abrev: 'ca' },
  { name: 'Chad', abrev: 'td' },
  { name: 'Chile', abrev: 'cl' },
  { name: 'China', abrev: 'cn' },
  { name: 'Chipre', abrev: 'cy' },
  { name: 'Ciudad del Vaticano (Santa Sede)', abrev: 'va' },
  { name: 'Colombia', abrev: 'co' },
  { name: 'Comores', abrev: 'km' },
  { name: 'Congo', abrev: 'cg' },
  { name: 'Congo, República Democrática del', abrev: 'cd' },
  { name: 'Corea', abrev: 'kr' },
  { name: 'Corea del Norte', abrev: 'kp' },
  { name: 'Costa de Marfil', abrev: 'ci' },
  { name: 'Costa Rica', abrev: 'cr' },
  { name: 'Croacia (Hrvatska)', abrev: 'hr' },
  { name: 'Cuba', abrev: 'cu' },
  { name: 'Dinamarca', abrev: 'dk' },
  { name: 'Djibouti', abrev: 'dj' },
  { name: 'Dominica', abrev: 'dm' },
  { name: 'Ecuador', abrev: 'ec' },
  { name: 'Egipto', abrev: 'eg' },
  { name: 'El Salvador', abrev: 'sv' },
  { name: 'Emiratos Árabes Unidos', abrev: 'ae' },
  { name: 'Eritrea', abrev: 'er' },
  { name: 'Eslovaquia', abrev: 'si' },
  { name: 'Eslovenia', abrev: 'es' },
  { name: 'España', abrev: 'es' },
  { name: 'Estados Unidos', abrev: 'us' },
  { name: 'Estonia', abrev: 'ee' },
  { name: 'Etiopía', abrev: 'et' },
  { name: 'Fiji', abrev: 'fj' },
  { name: 'Filipinas', abrev: 'ph' },
  { name: 'Finlandia', abrev: 'fi' },
  { name: 'Francia', abrev: 'fr' },
  { name: 'Gabón', abrev: 'ga' },
  { name: 'Gambia', abrev: 'gm' },
  { name: 'Georgia', abrev: 'ge' },
  { name: 'Ghana', abrev: 'gh' },
  { name: 'Gibraltar', abrev: 'gi' },
  { name: 'Granada', abrev: 'gd' },
  { name: 'Grecia', abrev: 'gr' },
  { name: 'Groenlandia', abrev: 'gl' },
  { name: 'Guadalupe', abrev: 'gp' },
  { name: 'Guam', abrev: 'gu' },
  { name: 'Guatemala', abrev: 'gt' },
  { name: 'Guayana', abrev: 'gy' },
  { name: 'Guayana Francesa', abrev: 'gf' },
  { name: 'Guinea', abrev: 'gn' },
  { name: 'Guinea Ecuatorial', abrev: 'gq' },
  { name: 'Guinea-Bissau', abrev: 'gw' },
  { name: 'Haití', abrev: 'ht' },
  { name: 'Honduras', abrev: 'hn' },
  { name: 'Hungría', abrev: 'hu' },
  { name: 'India', abrev: 'in' },
  { name: 'Indonesia', abrev: 'id' },
  { name: 'Irak', abrev: 'iq' },
  { name: 'Irán', abrev: 'ir' },
  { name: 'Irlanda', abrev: 'ie' },
  { name: 'Isla Bouvet', abrev: 'bv' },
  { name: 'Isla de Christmas', abrev: 'cx' },
  { name: 'Islandia', abrev: 'is' },
  { name: 'Islas Caimán', abrev: 'ky' },
  { name: 'Islas Cook', abrev: 'ck' },
  { name: 'Islas de Cocos o Keeling', abrev: 'cc' },
  { name: 'Islas Faroe', abrev: 'fo' },
  { name: 'Islas Heard y McDonald', abrev: 'hm' },
  { name: 'Islas Malvinas', abrev: 'fk' },
  { name: 'Islas Marianas del Norte', abrev: 'mp' },
  { name: 'Islas Marshall', abrev: 'mh' },
  { name: 'Islas menores de Estados Unidos', abrev: 'um' },
  { name: 'Islas Palau', abrev: 'pw' },
  { name: 'Islas Salomón', abrev: 'sb' },
  { name: 'Islas Svalbard y Jan Mayen', abrev: 'sj' },
  { name: 'Islas Tokelau', abrev: 'tk' },
  { name: 'Islas Turks y Caicos', abrev: 'tc' },
  { name: 'Islas Vírgenes (EEUU)', abrev: 'vi' },
  { name: 'Islas Vírgenes (Reino Unido)', abrev: 'vg' },
  { name: 'Islas Wallis y Futuna', abrev: 'wf' },
  { name: 'Israel', abrev: 'il' },
  { name: 'Italia', abrev: 'it' },
  { name: 'Jamaica', abrev: 'jm' },
  { name: 'Japón', abrev: 'jp' },
  { name: 'Jordania', abrev: 'jo' },
  { name: 'Kazajistán', abrev: 'kz' },
  { name: 'Kenia', abrev: 'ke' },
  { name: 'Kirguistán', abrev: 'kg' },
  { name: 'Kiribati', abrev: 'ki' },
  { name: 'Kuwait', abrev: 'kw' },
  { name: 'Laos', abrev: 'la' },
  { name: 'Lesotho', abrev: 'ls' },
  { name: 'Letonia', abrev: 'lv' },
  { name: 'Líbano', abrev: 'lb' },
  { name: 'Liberia', abrev: 'lr' },
  { name: 'Libia', abrev: 'ly' },
  { name: 'Liechtenstein', abrev: 'li' },
  { name: 'Lituania', abrev: 'lt' },
  { name: 'Luxemburgo', abrev: 'lu' },
  { name: 'Macedonia, Ex-República Yugoslava de', abrev: 'mk' },
  { name: 'Madagascar', abrev: 'mg' },
  { name: 'Malasia', abrev: 'my' },
  { name: 'Malawi', abrev: 'mw' },
  { name: 'Maldivas', abrev: 'mv' },
  { name: 'Malí', abrev: 'ml' },
  { name: 'Malta', abrev: 'mt' },
  { name: 'Marruecos', abrev: 'ma' },
  { name: 'Martinica', abrev: 'mq' },
  { name: 'Mauricio', abrev: 'mu' },
  { name: 'Mauritania', abrev: 'mr' },
  { name: 'Mayotte', abrev: 'yt' },
  { name: 'México', abrev: 'mx' },
  { name: 'Micronesia', abrev: 'fm' },
  { name: 'Moldavia', abrev: 'md' },
  { name: 'Mónaco', abrev: 'mc' },
  { name: 'Mongolia', abrev: 'mn' },
  { name: 'Montserrat', abrev: 'ms' },
  { name: 'Mozambique', abrev: 'mz' },
  { name: 'Namibia', abrev: 'na' },
  { name: 'Nauru', abrev: 'nr' },
  { name: 'Nepal', abrev: 'np' },
  { name: 'Nicaragua', abrev: 'ni' },
  { name: 'Níger', abrev: 'ne' },
  { name: 'Nigeria', abrev: 'ng' },
  { name: 'Niue', abrev: 'nu' },
  { name: 'Norfolk', abrev: 'nf' },
  { name: 'Noruega', abrev: 'no' },
  { name: 'Nueva Caledonia', abrev: 'nc' },
  { name: 'Nueva Zelanda', abrev: 'nz' },
  { name: 'Omán', abrev: 'om' },
  { name: 'Países Bajos', abrev: 'nl' },
  { name: 'Panamá', abrev: 'pa' },
  { name: 'Papúa Nueva Guinea', abrev: 'pg' },
  { name: 'Paquistán', abrev: 'pk' },
  { name: 'Paraguay', abrev: 'py' },
  { name: 'Perú', abrev: 'pe' },
  { name: 'Pitcairn', abrev: 'pn' },
  { name: 'Polinesia Francesa', abrev: 'pf' },
  { name: 'Polonia', abrev: 'pl' },
  { name: 'Portugal', abrev: 'pt' },
  { name: 'Puerto Rico', abrev: 'pr' },
  { name: 'Qatar', abrev: 'qa' },
  { name: 'Reino Unido', abrev: 'uk' },
  { name: 'República Centroafricana', abrev: 'cf' },
  { name: 'República Checa', abrev: 'cz' },
  { name: 'República de Sudáfrica', abrev: 'za' },
  { name: 'República Dominicana', abrev: 'do' },
  { name: 'República Eslovaca', abrev: 'sk' },
  { name: 'Reunión', abrev: 're' },
  { name: 'Ruanda', abrev: 'rw' },
  { name: 'Rumania', abrev: 'ro' },
  { name: 'Rusia', abrev: 'ru' },
  { name: 'Sahara Occidental', abrev: 'eh' },
  { name: 'Saint Kitts y Nevis', abrev: 'kn' },
  { name: 'Samoa', abrev: 'ws' },
  { name: 'Samoa Americana', abrev: 'as' },
  { name: 'San Marino', abrev: 'sm' },
  { name: 'San Vicente y Granadinas', abrev: 'vc' },
  { name: 'Santa Helena', abrev: 'sh' },
  { name: 'Santa Lucía', abrev: 'lc' },
  { name: 'Santo Tomé y Príncipe', abrev: 'st' },
  { name: 'Senegal', abrev: 'sn' },
  { name: 'Seychelles', abrev: 'sc' },
  { name: 'Sierra Leona', abrev: 'sl' },
  { name: 'Singapur', abrev: 'sg' },
  { name: 'Siria', abrev: 'sy' },
  { name: 'Somalia', abrev: 'so' },
  { name: 'Sri Lanka', abrev: 'lk' },
  { name: 'St Pierre y Miquelon', abrev: 'pm' },
  { name: 'Suazilandia', abrev: 'sz' },
  { name: 'Sudán', abrev: 'sd' },
  { name: 'Suecia', abrev: 'se' },
  { name: 'Suiza', abrev: 'ch' },
  { name: 'Surinam', abrev: 'sr' },
  { name: 'Tailandia', abrev: 'th' },
  { name: 'Taiwán', abrev: 'tw' },
  { name: 'Tanzania', abrev: 'tz' },
  { name: 'Tayikistán', abrev: 'tj' },
  { name: 'Territorios franceses del Sur', abrev: 'tf' },
  { name: 'Timor Oriental', abrev: 'tp' },
  { name: 'Togo', abrev: 'tg' },
  { name: 'Tonga', abrev: 'to' },
  { name: 'Trinidad y Tobago', abrev: 'tt' },
  { name: 'Túnez', abrev: 'tn' },
  { name: 'Turkmenistán', abrev: 'tm' },
  { name: 'Turquía', abrev: 'tr' },
  { name: 'Tuvalu', abrev: 'tv' },
  { name: 'Ucrania', abrev: 'ua' },
  { name: 'Uganda', abrev: 'ug' },
  { name: 'Uruguay', abrev: 'uy' },
  { name: 'Uzbekistán', abrev: 'uz' },
  { name: 'Vanuatu', abrev: 'vu' },
  { name: 'Venezuela', abrev: 've' },
  { name: 'Vietnam', abrev: 'vn' },
  { name: 'Yemen', abrev: 'ye' },
  { name: 'Yugoslavia', abrev: 'yu' },
  { name: 'Zambia', abrev: 'zm' },
  { name: 'Zimbabue', abrev: 'zw' },
];

const DEVICES = [
  { id: '0', nombre: 'Windows', device_icon: 'desktop_windows' },
  { id: '1', nombre: 'Macbook PRO', device_icon: 'laptop_mac' },
  { id: '2', nombre: 'Galaxy S23', device_icon: 'smartphone' },
  { id: '3', nombre: 'iPhone Pro', device_icon: 'phone_iphone' },
];

export { COUNTRIES_FLAGS, DEVICES };
